
------------------------------------
Your code has been rated at 10.00/10

************* Module load_pdf
pdf_report/load_pdf.py:116:0: C0301: Line too long (102/100) (line-too-long)
pdf_report/load_pdf.py:40:4: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
pdf_report/load_pdf.py:56:11: W0718: Catching too general exception Exception (broad-exception-caught)
pdf_report/load_pdf.py:56:4: W0612: Unused variable 'e' (unused-variable)
pdf_report/load_pdf.py:85:33: W0621: Redefining name 'cursor' from outer scope (line 16) (redefined-outer-name)
pdf_report/load_pdf.py:5:0: C0411: standard import "io.BytesIO" should be placed before third party import "dotenv.load_dotenv" (wrong-import-order)
pdf_report/load_pdf.py:6:0: C0411: standard import "datetime.datetime" should be placed before third party import "dotenv.load_dotenv" (wrong-import-order)
pdf_report/load_pdf.py:8:0: C0411: standard import "email.mime.application.MIMEApplication" should be placed before third party import "dotenv.load_dotenv" (wrong-import-order)
pdf_report/load_pdf.py:9:0: C0411: standard import "email.mime.multipart.MIMEMultipart" should be placed before third party import "dotenv.load_dotenv" (wrong-import-order)
pdf_report/load_pdf.py:10:0: C0411: standard import "email.mime.text.MIMEText" should be placed before third party import "dotenv.load_dotenv" (wrong-import-order)

-----------------------------------
Your code has been rated at 8.86/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module db_connection
archive/db_connection.py:44:15: W0718: Catching too general exception Exception (broad-exception-caught)
archive/db_connection.py:52:15: W0718: Catching too general exception Exception (broad-exception-caught)
archive/db_connection.py:52:8: W0612: Unused variable 'e' (unused-variable)

-----------------------------------
Your code has been rated at 8.89/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module sns_reporting
national_rail/sns_reporting.py:93:11: W0718: Catching too general exception Exception (broad-exception-caught)
national_rail/sns_reporting.py:97:0: R0913: Too many arguments (6/5) (too-many-arguments)
national_rail/sns_reporting.py:125:0: R0914: Too many local variables (19/15) (too-many-locals)
national_rail/sns_reporting.py:180:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.62/10

************* Module load_national
national_rail/load_national.py:58:11: W0718: Catching too general exception Exception (broad-exception-caught)
national_rail/load_national.py:105:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.63/10

************* Module national_rail
national_rail/national_rail.py:42:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.60/10

************* Module extract_national
national_rail/extract_national.py:8:0: W0611: Unused load_dotenv imported from dotenv (unused-import)

-----------------------------------
Your code has been rated at 9.62/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

************* Module realtime_trains
realtime_trains/realtime_trains.py:36:11: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.47/10

************* Module load_real
realtime_trains/load_real.py:53:0: R0914: Too many local variables (24/15) (too-many-locals)
realtime_trains/load_real.py:136:11: W0718: Catching too general exception Exception (broad-exception-caught)
realtime_trains/load_real.py:240:0: R0913: Too many arguments (6/5) (too-many-arguments)
realtime_trains/load_real.py:265:15: W0718: Catching too general exception Exception (broad-exception-caught)

-----------------------------------
Your code has been rated at 9.67/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10


------------------------------------
Your code has been rated at 10.00/10

