============================= test session starts ==============================
platform linux -- Python 3.12.4, pytest-8.3.1, pluggy-1.5.0
rootdir: /home/runner/work/Railway-Tracker/Railway-Tracker
collected 58 items

<<<<<<< HEAD
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.39s ===============================
=======
national_rail/test_load.py ......                                        [ 10%]
national_rail/test_transform.py ...................                      [ 43%]
realtime_trains/test_extract_real.py ......                              [ 53%]
realtime_trains/test_load_real.py .........                              [ 68%]
realtime_trains/test_transform_real.py .................                 [ 98%]
test_file.py .                                                           [100%]

============================== 58 passed in 0.32s ==============================
>>>>>>> d770dd7862e4945b588aea82c16b84aa00f96bea
